-- AlterTable
ALTER TABLE "site_settings" ADD COLUMN     "cnss" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "ice" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "legalAddress" TEXT NOT NULL DEFAULT '46 AV OKBA ET G 3 APT 18 AGDAL RABAT',
ADD COLUMN     "legalCapital" TEXT NOT NULL DEFAULT '100 000,00 DH',
ADD COLUMN     "legalForm" TEXT NOT NULL DEFAULT 'SARL AU',
ADD COLUMN     "legalName" TEXT NOT NULL DEFAULT 'Nahda Smart',
ADD COLUMN     "patente" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "rc" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "rcCity" TEXT NOT NULL DEFAULT 'Rabat',
ADD COLUMN     "taxId" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "vatRate" DECIMAL(5,2) NOT NULL DEFAULT 20;
